# Generated by Django 3.1.8 on 2022-05-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20220510_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapp',
            name='status',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
