# Generated by Django 3.1.8 on 2022-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20220510_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapp',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
