# Generated by Django 3.1.8 on 2022-05-27 03:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('billing_address', models.CharField(max_length=200)),
                ('shipping_address', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=100)),
                ('gst_no', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=100)),
                ('delivery_terms', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
    ]
