# Generated by Django 4.0.4 on 2022-04-27 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('machine', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('batch_no', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('drum_fill', models.IntegerField()),
                ('batch_hours', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('production_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionplant')),
            ],
        ),
    ]
