# Generated by Django 3.1.8 on 2022-05-27 03:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('select_branch', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('unique_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('reserved_qt', models.CharField(max_length=100)),
                ('max_quantity', models.CharField(max_length=100)),
                ('available_quantity', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Total Inventory',
            },
        ),
        migrations.CreateModel(
            name='UtilityInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.CharField(default=None, max_length=40, null=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('reserved_qt', models.IntegerField()),
                ('max_quantity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('select_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.branch')),
            ],
            options={
                'verbose_name_plural': 'Utility Inventory',
            },
        ),
        migrations.CreateModel(
            name='RawInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.CharField(default=None, max_length=40, null=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('reserved_qt', models.IntegerField()),
                ('max_quantity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('select_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.branch')),
            ],
            options={
                'verbose_name_plural': 'Raw Inventory',
            },
        ),
        migrations.CreateModel(
            name='FinishedInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.CharField(default=None, max_length=40, null=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('reserved_qt', models.IntegerField()),
                ('max_quantity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('select_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.branch')),
            ],
            options={
                'verbose_name_plural': 'Finished Inventory',
            },
        ),
    ]
