# Generated by Django 3.1.8 on 2022-06-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20220527_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
