# Generated by Django 4.0.4 on 2022-04-22 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('customer', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformaInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('piNo', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('gstNo', models.CharField(blank=True, max_length=30, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('phonePerson', models.CharField(blank=True, max_length=13, null=True)),
                ('deliveryAdd', models.CharField(blank=True, max_length=100, null=True)),
                ('emailId', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.totalinventory')),
                ('selectCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('select_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.branch')),
            ],
            options={
                'verbose_name_plural': 'Performa Invoice Basic',
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('saleNo', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('gstNo', models.CharField(blank=True, max_length=30, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('phonePerson', models.CharField(blank=True, max_length=13, null=True)),
                ('emailId', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('deliveryAt', models.CharField(blank=True, max_length=100, null=True)),
                ('creditNo', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentTerms', models.CharField(blank=True, max_length=100, null=True)),
                ('freight', models.CharField(blank=True, max_length=100, null=True)),
                ('transportDetails', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loadingFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.branch')),
                ('piRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.performainvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.totalinventory')),
                ('selectCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name_plural': 'Sales Order',
            },
        ),
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approve', 'Approve'), ('Dis-Approve', 'Dis-Approve'), ('Dispatch', 'Dispatch'), ('Delivered', 'Delivered')], default='Reserved', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saleNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.CharField(max_length=100)),
                ('reserved_qt', models.CharField(max_length=100)),
                ('available_quantity', models.CharField(max_length=100)),
                ('customer_quantity', models.CharField(max_length=100)),
                ('destination_add', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=12)),
                ('loggedIn', models.CharField(max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.totalinventory')),
                ('select_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.branch')),
            ],
            options={
                'verbose_name_plural': 'Sales Planning',
            },
        ),
    ]
